# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ycstl_config = debug
  ycstl_test_config = debug

else ifeq ($(config),release)
  ycstl_config = release
  ycstl_test_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ycstl ycstl-test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ycstl:
ifneq (,$(ycstl_config))
	@echo "==== Building ycstl ($(ycstl_config)) ===="
	@${MAKE} --no-print-directory -C . -f ycstl.make config=$(ycstl_config)
endif

ycstl-test: ycstl
ifneq (,$(ycstl_test_config))
	@echo "==== Building ycstl-test ($(ycstl_test_config)) ===="
	@${MAKE} --no-print-directory -C ycstl-test -f Makefile config=$(ycstl_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f ycstl.make clean
	@${MAKE} --no-print-directory -C ycstl-test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ycstl"
	@echo "   ycstl-test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"